from typing import overload

# from aqmodels._core import Expression

class Variable:
    def __init__(
        self,
        name: str,
        env: Environment | None = ...,
        vtype: Vtype | None = ...,
        bounds: Bounds | None = ...,
    ) -> None: ...
    @overload
    def __new__(
        cls, name: str, vtype: Vtype | None = ..., bounds: Bounds | None = ...
    ) -> Variable: ...
    @overload
    def __new__(
        cls,
        name: str,
        env: Environment,
        vtype: Vtype | None = ...,
        bounds: Bounds | None = ...,
    ) -> Variable: ...
    # addition
    @overload
    def __add__(self, other: Variable) -> Expression: ...
    @overload
    def __add__(self, other: Expression) -> Expression: ...
    @overload
    def __add__(self, other: int) -> Expression: ...
    @overload
    def __add__(self, other: float) -> Expression: ...
    @overload
    def __radd__(self, other: int) -> Expression: ...
    @overload
    def __radd__(self, other: float) -> Expression: ...
    # subtraction
    @overload
    def __sub__(self, other: Variable) -> Expression: ...
    @overload
    def __sub__(self, other: int) -> Expression: ...
    @overload
    def __sub__(self, other: float) -> Expression: ...
    @overload
    def __rsub__(self, other: int) -> Expression: ...
    @overload
    def __rsub__(self, other: float) -> Expression: ...
    # multiplication
    @overload
    def __mul__(self, other: Expression) -> Expression: ...
    @overload
    def __mul__(self, other: Variable) -> Expression: ...
    @overload
    def __mul__(self, other: int) -> Expression: ...
    @overload
    def __mul__(self, other: float) -> Expression: ...
    @overload
    def __rmul__(self, other: int) -> Expression: ...
    @overload
    def __rmul__(self, other: float) -> Expression: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
