# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      cargo:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "uv"
    directory: "/py-lunamodel"
    schedule:
      interval: "weekly"
    exclude-paths:
      - "THIRD_PARTY_LICENSES.txt"
    groups:
      python:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "bun"
    directory: "/js-lunamodel"
    schedule:
      interval: "weekly"
    groups:
      javascript:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
