repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: uv run --directory py-lunamodel ruff format --check .
        language: system
        pass_filenames: false
        always_run: true
        types_or: [python, pyi]

      - id: ruff-check
        name: ruff check
        entry: uv run --directory py-lunamodel ruff check .
        language: system
        pass_filenames: false
        always_run: true
        types_or: [python, pyi]

      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all -- --check
        language: system
        pass_filenames: false
        always_run: true
        types: [rust]

      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --workspace --all-targets -- -D warnings
        language: system
        pass_filenames: false
        always_run: true
        types: [rust]
