from luna_model._lm import (
    PyLunaModelError, 
    PyVariableOutOfRangeError,
    PyUnsupportedOperationError,
    PyComputationError,
    PyComputationError,
    PyDecodeError,
    PyDifferentEnvsError,
    PyDuplicateConstraintNameError,
    PyEvaluationError,
    PyIllegalConstraintNameError,
    PyInternalPanicError,
    PyModelNotQuadraticError,
    PyModelNotUnconstrainedError,
    PyModelSenseNotMinimizeError,
    PyModelVtypeError,
    PyMultipleActiveEnvironmentsError,
    PyNoActiveEnvironmentFoundError,
    PyNoConstraintForKeyError,
    PySampleColCreationError,
    PySampleIncompatibleVtypeError,
    PySampleIncorrectLengthError,
    PySampleUnexpectedVariableError,
    PySolutionTranslationError,
    PyTranslationError,
    PyVariableCreationError,
    PyVariableExistsError,
    PyVariableNamesError,
    PyVariableNotExistingError,
    PyVariableOutOfRangeError,
    PyVariablesFromDifferentEnvsError,
    PyStartCannotBeInferredError,
)

class LunaModelError(PyLunaModelError): ...
class VariableOutOfRangeError(PyVariableOutOfRangeError): ...
class VariableExistsError(PyVariableExistsError): ...
class VariableNotExistingError(PyVariableNotExistingError): ...
class VariableCreationError(PyVariableCreationError): ...
class VariablesFromDifferentEnvsError(PyVariablesFromDifferentEnvsError): ...
class DifferentEnvsError(PyDifferentEnvsError):...
class NoActiveEnvironmentFoundError(PyNoActiveEnvironmentFoundError): ...
class MultipleActiveEnvironmentsError(PyMultipleActiveEnvironmentsError): ...
class DecodeError(PyDecodeError): ...
class VariableNamesError(PyVariableNamesError): ...
class IllegalConstraintNameError(PyIllegalConstraintNameError): ...
class TranslationError(PyTranslationError): ...
class ModelNotQuadraticError(PyModelNotQuadraticError): ...
class ModelNotUnconstrainedError(PyModelNotUnconstrainedError): ...
class ModelSenseNotMinimizeError(PyModelSenseNotMinimizeError): ...
class ModelVtypeError(PyModelVtypeError): ...
class SolutionTranslationError(PySolutionTranslationError): ...
class SampleIncorrectLengthError(PySampleIncorrectLengthError, SolutionTranslationError): ...
class SampleUnexpectedVariableError(PySampleUnexpectedVariableError, SolutionTranslationError): ...
class SampleIncompatibleVtypeError(PySampleIncompatibleVtypeError, SolutionTranslationError): ...
class UnsupportedOperationError(PyUnsupportedOperationError): ...
class ComputationError(PyComputationError): ...
class EvaluationError(PyEvaluationError): ...
class DuplicateConstraintNameError(PyDuplicateConstraintNameError): ...
class StartCannotBeInferredError(PyStartCannotBeInferredError, TypeError): ...
class NoConstraintForKeyError(PyNoConstraintForKeyError, IndexError): ...
class SampleColCreationError(PySampleColCreationError, IndexError): ...
class InternalPanicError(PyInternalPanicError, RuntimeError): ...
# class CompilationError(PyCompilationError, RuntimeError): ...
# class EnvMismatchError(PyEnvMismatchError, RuntimeError): ...

__all__ = [
    "ComputationError",
    "ComputationError",
    "DecodeError",
    "DifferentEnvsError",
    "DuplicateConstraintNameError",
    "EvaluationError",
    "IllegalConstraintNameError",
    "InternalPanicError",
    "ModelNotQuadraticError",
    "ModelNotUnconstrainedError",
    "ModelSenseNotMinimizeError",
    "ModelVtypeError",
    "MultipleActiveEnvironmentsError",
    "NoActiveEnvironmentFoundError",
    "NoConstraintForKeyError",
    "SampleColCreationError",
    "SampleIncompatibleVtypeError",
    "SampleIncorrectLengthError",
    "SampleUnexpectedVariableError",
    "SolutionTranslationError",
    "TranslationError",
    "VariableCreationError",
    "VariableExistsError",
    "VariableNamesError",
    "VariableNotExistingError",
    "VariableOutOfRangeError",
    "VariablesFromDifferentEnvsError",
]

