from typing import overload
from .environment import Environment
from .variable import Variable

class Expression:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, data: Environment) -> None: ...
    def __init__(self, data: Environment | None = None) -> None: ...
    @overload
    @staticmethod
    def const(val: float, /) -> Expression: ...
    @overload
    @staticmethod
    def const(val: float, /, env: Environment) -> Expression: ...
    @staticmethod
    def const(val: float, /, env: Environment | None = None) -> Expression: ...
    @property
    def environment(self) -> Environment: ...
    def get_offset(self) -> float: ...
    def get_linear(self, /, variable: Variable) -> float: ...
    def get_quadratic(self, /, u: Variable, v: Variable) -> float: ...
    def get_higher_order(self, /, *variables: tuple[Variable, ...]) -> float: ...
