name: Use Case
description: File a Use Case
labels: ["use case"]
body:
  - type: markdown
    attributes:
      values: |
        A use case describes a real use case that is difficult or impossible, but does not propose a solution.
        ## Remember to search before filing a new use case
        Please search for this use case in the issue tracker, and us a use case title that
        would have made your use case turn up in the search results for your search query.
  - type: textarea
    id: diagnosis
    attributes:
      label: Problem Diagnosis
      description: Describe the problem domain, describe clearly what kind of issues exist currently that you would like to be adressed. Be as specific as possible and provide as many details and examples as possible. Start with a high-level overview of the context and then incrementally get more specific.
      placeholder: Describe the problem domain and the problem that you want to be solved.
      validations:
        required: true
  - type: textarea
    id: treatment
    attributes:
      label: Expected Behavior
      description: Describe how you would evaluate the problem to be resolved. What will the users gain from your proposal that they are lacking now?
    validations:
      required: true
