from __future__ import annotations
from typing import TYPE_CHECKING, Protocol


if TYPE_CHECKING:
    from luna_model.solution.sample import Sample
    from numpy.typing import NDArray


class Result(Protocol):
    @property
    def sample(self) -> Sample: ...
    @property
    def obj_value(self) -> float | None: ...
    @property
    def constraints(self) -> NDArray | None: ...
    @property
    def variable_bounds(self) -> NDArray | None: ...
    @property
    def feasible(self) -> bool | None: ...


class ResultView(Result, Protocol):
    @property
    def counts(self, /) -> int: ...
    @property
    def obj_value(self, /) -> float | None: ...
    @property
    def raw_energy(self, /) -> float | None: ...
    @property
    def constraints(self, /) -> dict[str, bool] | None: ...
    @property
    def variable_bounds(self, /) -> dict[str, bool] | None: ...
    @property
    def feasible(self, /) -> bool | None: ...
    @property
    def sample(self, /) -> Sample: ...

    def __str__(self, /) -> str: ...
    def __repr__(self, /) -> str: ...
    def __eq__(self, other: ResultView, /) -> bool: ...  # type: ignore[reportIncompatibleMethodOverride]


class ResultIter(Protocol):
    def __iter__(self) -> ResultIter: ...
    def __next__(self) -> ResultView: ...
