from __future__ import annotations

from typing import TYPE_CHECKING, Protocol, overload

if TYPE_CHECKING:
    from luna_model.variable import Variable


class Sample(Protocol):
    def to_dict(self) -> dict[str, int | float]: ...
    def __getitem__(self, item: int | Variable | str) -> int | float: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> SampleIter: ...
    def __str__(self, /) -> str: ...


class Samples(Protocol):
    def tolist(self) -> list[list[int | float]]: ...
    @overload
    def __getitem__(self, item: int) -> Sample: ...
    @overload
    def __getitem__(self, item: tuple[int, int]) -> float: ...
    def __getitem__(self, item: int | tuple[int, int]) -> Sample | float: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> SamplesIter: ...


class SamplesIter(Protocol):
    def __iter__(self) -> SamplesIter: ...
    def __next__(self) -> Sample: ...


class SampleIter:
    def __iter__(self) -> SampleIter: ...
    def __next__(self) -> int | float: ...
