from __future__ import annotations
from typing import Protocol

from luna_model._lm import Variable


class Sample(Protocol):
    def __getitem__(self, item: int | Variable | str) -> int | float: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> SampleIter: ...
    def to_dict(self) -> dict[str, int | float]: ...


class Samples(Protocol):
    def tolist(self) -> list[list[int | float]]: ...
    def __getitem__(self, item: int | tuple[int, int]) -> int | float: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> SamplesIter: ...


class SamplesIter(Protocol):
    def __iter__(self) -> SamplesIter: ...
    def __next__(self) -> Sample: ...


class SampleIter:
    def __iter__(self) -> SampleIter: ...
    def __next__(self) -> int | float: ...
