/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Column-oriented solution data for model evaluation or solver results.
 *
 * A solution is independent of the original model and stores all variable data
 * by variable name. JavaScript solutions are created from LunaModel's binary
 * serializer with `Solution.deserialize()`.
 */
export declare class Solution {
  /**
   * Decode a LunaModel solution from serialized binary bytes.
   *
   * This is the JavaScript alias for Python's `Solution.decode()` /
   * `Solution.deserialize()` path. `data` must contain bytes produced by the
   * existing LunaModel `Solution` serializer.
   */
  static deserialize(data: Uint8Array): Solution
  /**
   * Number of occurrences for each stored sample row.
   *
   * This matches the Python `counts` property.
   */
  get counts(): Array<number>
  /**
   * Objective values as computed by the solver.
   *
   * Returns `null` if the solver did not provide raw energies. This matches
   * the Python `raw_energies` property.
   */
  get rawEnergies(): Array<number> | null
  /**
   * Objective values as computed by the corresponding model.
   *
   * Returns `null` for solutions that have not yet been evaluated. This
   * matches the Python `obj_values` property.
   */
  get objValues(): Array<number> | null
  /**
   * Feasibility flag for each stored sample row.
   *
   * A value is `true` when all constraints and variable bounds are satisfied
   * for that sample. Returns `null` for solutions without feasibility data.
   */
  get feasible(): Array<boolean> | null
  /**
   * Per-constraint feasibility flags keyed by constraint name.
   *
   * Each vector is aligned with the stored sample rows.
   */
  get constraints(): Record<string, Array<boolean>>
  /**
   * Per-variable bound feasibility flags keyed by variable name.
   *
   * Each vector is aligned with the stored sample rows.
   */
  get variableBounds(): Record<string, Array<boolean>>
  /**
   * Runtime metrics carried by this solution.
   *
   * Returns `null` if no timing metadata is available. This corresponds to
   * Python's `runtime` property.
   */
  get timing(): JsTiming | null
  /**
   * Fraction of total sample mass marked as feasible.
   *
   * Computes the count-weighted ratio of feasible samples to all samples.
   * Throws if feasibility data is not available.
   */
  feasibilityRatio(): number
  /**
   * Return a new solution containing only feasible sample rows.
   *
   * Throws if feasibility data is not available. Filtering feasible samples
   * is not possible on a non-evaluated solution.
   */
  filterFeasible(): Solution
}
export type JsSolution = Solution

/**
 * Runtime timing metadata attached to a solution.
 *
 * JavaScript exposes wall-clock timestamps as `Date` objects and durations as
 * numeric seconds.
 */
export declare class Timing {
  /**
   * Wall-clock start time.
   *
   * This matches Python's `start` property.
   */
  get start(): Date
  /**
   * Wall-clock end time.
   *
   * This matches Python's `end` property.
   */
  get end(): Date
  /**
   * Total runtime in seconds.
   *
   * This is computed as the difference between `end` and `start`. Throws if
   * the timing record is inconsistent and the total duration cannot be
   * computed. This matches Python's `total_seconds` property.
   */
  get totalSeconds(): number
  /**
   * QPU usage time reported by the backend.
   *
   * Returns `null` when no QPU timing was provided. This matches Python's
   * `qpu` property.
   */
  get qpu(): number | null
}
export type JsTiming = Timing
