from typing import overload

class Expression:
    @overload
    def __add__(self, other: Expression) -> Expression: ...
    @overload
    def __add__(self, other: int) -> Expression: ...
    @overload
    def __add__(self, other: float) -> Expression: ...

class Environment:
    def __init__(self) -> None: ...

class Variable:
    @overload
    def __new__(cls, name: str) -> Variable: ...
    @overload
    def __new__(cls, name: str, environment: Environment) -> Variable: ...
    @overload
    def __init__(self, name: str) -> None: ...
    @overload
    def __init__(self, name: str, environment: Environment) -> None: ...
    def __str__(self) -> str: ...
    @overload
    def __mul__(self, other: int) -> Expression: ...
    @overload
    def __mul__(self, other: float) -> Expression: ...
    @overload
    def __add__(self, other: int) -> Expression: ...
    @overload
    def __add__(self, other: float) -> Expression: ...
    @overload
    def __sub__(self, other: int) -> Expression: ...
    @overload
    def __sub__(self, other: float) -> Expression: ...
