from typing import overload
from ._core import Vtype, Bounds

class VariableExistsException(Exception):
    def __str__(self) -> str: ...

class Expression:
    # addition
    @overload
    def __add__(self, other: Expression) -> Expression: ...
    @overload
    def __add__(self, other: int) -> Expression: ...
    @overload
    def __add__(self, other: float) -> Expression: ...
    @overload
    # right addition
    def __radd__(self, other: Expression) -> Expression: ...
    @overload
    def __radd__(self, other: int) -> Expression: ...
    @overload
    def __radd__(self, other: float) -> Expression: ...
    # self addition
    @overload
    def __iadd__(self, other: Expression) -> Expression: ...
    @overload
    def __iadd__(self, other: int) -> Expression: ...
    @overload
    def __iadd__(self, other: float) -> Expression: ...
    # multiplication
    @overload
    def __mul__(self, other: Expression) -> Expression: ...
    @overload
    def __mul__(self, other: int) -> Expression: ...
    @overload
    def __mul__(self, other: float) -> Expression: ...
    # right multiplication
    @overload
    def __rmul__(self, other: Expression) -> Expression: ...
    @overload
    def __rmul__(self, other: int) -> Expression: ...
    @overload
    def __rmul__(self, other: float) -> Expression: ...
    # self multiplication
    @overload
    def __imul__(self, other: Expression) -> Expression: ...
    @overload
    def __imul__(self, other: int) -> Expression: ...
    @overload
    def __imul__(self, other: float) -> Expression: ...
    # subtraction
    @overload
    def __sub__(self, other: Expression) -> Expression: ...
    @overload
    def __sub__(self, other: int) -> Expression: ...
    @overload
    def __sub__(self, other: float) -> Expression: ...
    # right subtraction
    @overload
    def __rsub__(self, other: Expression) -> Expression: ...
    @overload
    def __rsub__(self, other: int) -> Expression: ...
    @overload
    def __rsub__(self, other: float) -> Expression: ...
    # self subtraction
    @overload
    def __isub__(self, other: Expression) -> Expression: ...
    @overload
    def __isub__(self, other: int) -> Expression: ...
    @overload
    def __isub__(self, other: float) -> Expression: ...

class Environment:
    def __init__(self) -> None: ...

class Variable:
    @overload
    def __new__(
        cls, name: str, vtype: Vtype | None = ..., bounds: Bounds | None = ...
    ) -> Variable: ...
    @overload
    def __new__(
        cls,
        name: str,
        environment: Environment,
        vtype: Vtype | None = ...,
        bounds: Bounds | None = ...,
    ) -> Variable: ...

    # @overload
    # def __new__(cls, name: str) -> Variable: ...
    # @overload
    # def __new__(cls, name: str, environment: Environment) -> Variable: ...
    # @overload
    # def __init__(self, name: str) -> None: ...
    # @overload
    # def __init__(self, name: str, environment: Environment) -> None: ...
    # def __str__(self) -> str: ...
    # # Multiplication
    # @overload
    # def __mul__(self, other: Variable) -> Expression: ...
    # @overload
    # def __mul__(self, other: int) -> Expression: ...
    # @overload
    # def __mul__(self, other: float) -> Expression: ...
    # @overload
    # def __rmul__(self, other: int) -> Expression: ...
    # @overload
    # def __rmul__(self, other: float) -> Expression: ...
    # @overload
    # def __add__(self, other: int) -> Expression: ...
    # @overload
    # def __add__(self, other: float) -> Expression: ...
    # @overload
    # def __radd__(self, other: int) -> Expression: ...
    # @overload
    # def __radd__(self, other: float) -> Expression: ...
    # @overload
    # def __sub__(self, other: int) -> Expression: ...
    # @overload
    # def __sub__(self, other: float) -> Expression: ...
