from enum import Enum
from typing import overload

class Vtype(Enum):
    Real = ...
    Integer = ...
    Binary = ...
    Spin = ...

class Bounds:
    def __init__(self, lower: float, upper: float) -> None: ...

class Expression:
    @overload
    def __add__(self, other: int) -> Expression: ...
    @overload
    def __add__(self, other: float) -> Expression: ...

class Variable:
    @overload
    def __init__(
        self, name: str, vtype: Vtype | None = ..., bounds: Bounds | None = ...
    ) -> None: ...
    @overload
    def __init__(
        self,
        name: str,
        env: Environment,
        vtype: Vtype | None = ...,
        bounds: Bounds | None = ...,
    ) -> None: ...
    @overload
    def __new__(
        cls, name: str, vtype: Vtype | None = ..., bounds: Bounds | None = ...
    ) -> Variable: ...
    @overload
    def __new__(
        cls,
        name: str,
        env: Environment,
        vtype: Vtype | None = ...,
        bounds: Bounds | None = ...,
    ) -> Variable: ...
    @overload
    def __add__(self, other: Variable) -> Expression: ...
    @overload
    def __add__(self, other: int) -> Expression: ...
    @overload
    def __add__(self, other: float) -> Expression: ...

class Environment: ...
