from enum import Enum
from typing import overload
from numpy.typing import NDArray

class Vtype(Enum):
    Real = ...
    Integer = ...
    Binary = ...
    Spin = ...

class Bounds:
    def __init__(self, lower: float, upper: float) -> None: ...

class Expression:
    def get_linear(self, variable: Variable) -> float: ...
    def num_variables(self) -> int: ...
    # @overload
    # def __add__(self, other: int) -> Expression: ...
    # @overload
    # def __add__(self, other: float) -> Expression: ...

class Variable:
    @overload
    def __init__(
        self, name: str, vtype: Vtype | None = ..., bounds: Bounds | None = ...
    ) -> None: ...
    @overload
    def __init__(
        self,
        name: str,
        env: Environment,
        vtype: Vtype | None = ...,
        bounds: Bounds | None = ...,
    ) -> None: ...
    @overload
    def __new__(
        cls, name: str, vtype: Vtype | None = ..., bounds: Bounds | None = ...
    ) -> Variable: ...
    @overload
    def __new__(
        cls,
        name: str,
        env: Environment,
        vtype: Vtype | None = ...,
        bounds: Bounds | None = ...,
    ) -> Variable: ...
    @overload
    def __add__(self, other: Variable) -> Expression: ...
    @overload
    def __add__(self, other: int) -> Expression: ...
    @overload
    def __add__(self, other: float) -> Expression: ...

class Environment: ...
class Model: ...

class MatrixTranslator:
    @staticmethod
    def to_model(qubo: NDArray, name: str | None = ...) -> Model: ...
