# This file is auto-generated.
# Do not edit manually.

from enum import Enum
from typing import Any
from typing import overload

from . import errors
from . import translator

class Expression: ...
class Environment:
    def __init__(self) -> None: ...
    def __enter__(self) -> Any: ...
    def __exit__(self, exc_type, exc_value, exc_traceback) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    @overload
    def serialize(self) -> bytes: ...
    @overload
    def serialize(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def serialize(self, level: int | None = ...) -> bytes: ...
    @overload
    def serialize(
        self, compress: bool | None = ..., level: int | None = ...
    ) -> bytes: ...
    @overload
    def encode(self) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def encode(self, level: int | None = ...) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ..., level: int | None = ...) -> bytes: ...
    @staticmethod
    def deserialize(data: bytes) -> Expression: ...
    @staticmethod
    def decode(data: bytes) -> Expression: ...
class Vtype(Enum):
    Real = ...
    Integer = ...
    Binary = ...
    Spin = ...

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
class Variable:
    def __init__(
        self,
        name: str,
        env: Environment | None = ...,
        vtype: Vtype | None = ...,
        bounds: Bounds | None = ...,
    ) -> None: ...
    @overload
    def __new__(
        cls, name: str, vtype: Vtype | None = ..., bounds: Bounds | None = ...
    ) -> Variable: ...
    @overload
    def __new__(
        cls,
        name: str,
        env: Environment,
        vtype: Vtype | None = ...,
        bounds: Bounds | None = ...,
    ) -> Variable: ...
    # addition
    @overload
    def __add__(self, other: Variable) -> Expression: ...
    @overload
    def __add__(self, other: Expression) -> Expression: ...
    @overload
    def __add__(self, other: int) -> Expression: ...
    @overload
    def __add__(self, other: float) -> Expression: ...
    @overload
    def __radd__(self, other: int) -> Expression: ...
    @overload
    def __radd__(self, other: float) -> Expression: ...
    # subtraction
    @overload
    def __sub__(self, other: Variable) -> Expression: ...
    @overload
    def __sub__(self, other: int) -> Expression: ...
    @overload
    def __sub__(self, other: float) -> Expression: ...
    @overload
    def __rsub__(self, other: int) -> Expression: ...
    @overload
    def __rsub__(self, other: float) -> Expression: ...
    # multiplication
    @overload
    def __mul__(self, other: Expression) -> Expression: ...
    @overload
    def __mul__(self, other: Variable) -> Expression: ...
    @overload
    def __mul__(self, other: int) -> Expression: ...
    @overload
    def __mul__(self, other: float) -> Expression: ...
    @overload
    def __rmul__(self, other: int) -> Expression: ...
    @overload
    def __rmul__(self, other: float) -> Expression: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
class MatrixTranslator:
    def __init__(self) -> None: ...
class VariableOutOfRangeError(Exception):
    def __str__(self) -> str: ...
class VariableExistsError(Exception):
    def __str__(self) -> str: ...

__all__ = [
    "Environment",
    "Expression",
    "MatrixTranslator",
    "Variable",
    "VariableExistsError",
    "VariableOutOfRangeError",
    "Vtype",
    "errors",
    "translator",
]