from enum import Enum
from typing import overload

from aqmodels._expression import Expression

class Comparator(Enum):
    Eq = ...
    Leq = ...
    Geq = ...

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Constraint:
    def __init__(self, lhs: Expression, rhs: float, comparator: Comparator) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Constraints:
    def add_constraint(self, constraint: Constraint): ...
    @overload
    def encode(self) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def encode(self, level: int | None = ...) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ..., level: int | None = ...) -> bytes: ...
    @overload
    def serialize(self) -> bytes: ...
    @overload
    def serialize(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def serialize(self, level: int | None = ...) -> bytes: ...
    @overload
    def serialize(
        self, compress: bool | None = ..., level: int | None = ...
    ) -> bytes: ...
    @staticmethod
    def decode(data: bytes) -> Expression: ...
    @staticmethod
    def deserialize(data: bytes) -> Expression: ...
    def __iadd__(self, constraint: Constraint): ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __getitem__(self, item: int) -> Constraint: ...
