from enum import Enum
from typing import overload

from aqmodels import Expression, Environment
from aqmodels import Variable

class Comparator(Enum):
    Eq = ...
    Le = ...
    Ge = ...

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Constraint:
    @overload
    def __init__(
        self, lhs: Expression, rhs: Expression, comparator: Comparator
    ) -> None: ...
    @overload
    def __init__(
        self, lhs: Expression, rhs: Variable, comparator: Comparator
    ) -> None: ...
    @overload
    def __init__(self, lhs: Expression, rhs: int, comparator: Comparator) -> None: ...
    @overload
    def __init__(self, lhs: Expression, rhs: float, comparator: Comparator) -> None: ...
    @overload
    def __init__(
        self, lhs: Expression, rhs: Expression, comparator: Comparator, name: str
    ) -> None: ...
    @overload
    def __init__(
        self, lhs: Expression, rhs: Variable, comparator: Comparator, name: str
    ) -> None: ...
    @overload
    def __init__(
        self, lhs: Expression, rhs: int, comparator: Comparator, name: str
    ) -> None: ...
    @overload
    def __init__(
        self, lhs: Expression, rhs: float, comparator: Comparator, name: str
    ) -> None: ...
    @overload
    def __init__(
        self, lhs: Variable, rhs: Expression, comparator: Comparator
    ) -> None: ...
    @overload
    def __init__(
        self, lhs: Variable, rhs: Variable, comparator: Comparator
    ) -> None: ...
    @overload
    def __init__(self, lhs: Variable, rhs: int, comparator: Comparator) -> None: ...
    @overload
    def __init__(self, lhs: Variable, rhs: float, comparator: Comparator) -> None: ...
    @overload
    def __init__(
        self, lhs: Variable, rhs: Expression, comparator: Comparator, name: str
    ) -> None: ...
    @overload
    def __init__(
        self, lhs: Variable, rhs: Variable, comparator: Comparator, name: str
    ) -> None: ...
    @overload
    def __init__(
        self, lhs: Variable, rhs: int, comparator: Comparator, name: str
    ) -> None: ...
    @overload
    def __init__(
        self, lhs: Variable, rhs: float, comparator: Comparator, name: str
    ) -> None: ...
    def __eq__(self, other: Constraint) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    @property
    def name(self) -> str | None: ...
    @property
    def lhs(self) -> Expression: ...
    @property
    def rhs(self) -> float: ...
    @property
    def comparator(self) -> Comparator: ...

class Constraints:
    def __init__(self) -> None: ...
    @overload
    def add_constraint(self, constraint: Constraint): ...
    @overload
    def add_constraint(self, constraint: Constraint, name: str | None = ...): ...
    @overload
    def encode(self) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def encode(self, level: int | None = ...) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ..., level: int | None = ...) -> bytes: ...
    @overload
    def serialize(self) -> bytes: ...
    @overload
    def serialize(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def serialize(self, level: int | None = ...) -> bytes: ...
    @overload
    def serialize(
        self, compress: bool | None = ..., level: int | None = ...
    ) -> bytes: ...
    @staticmethod
    def decode(data: bytes, env: Environment) -> Expression: ...
    @staticmethod
    def deserialize(data: bytes, env: Environment) -> Expression: ...
    @overload
    def __iadd__(self, constraint: Constraint): ...
    @overload
    def __iadd__(self, constraint: tuple[Constraint, str]): ...
    def __eq__(self, other: Constraints) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __getitem__(self, item: int) -> Constraint: ...
