from enum import Enum
from typing import overload

from aqmodels import Variable
from aqmodels._expression import Expression

class Comparator(Enum):
    Eq = ...
    Le = ...
    Ge = ...

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Constraint:
    @overload
    def __init__(self, lhs: Expression, rhs: float, comparator: Comparator) -> None: ...
    @overload
    def __init__(self, lhs: Variable, rhs: float, comparator: Comparator) -> None: ...
    @overload
    def __init__(
        self, lhs: Expression, rhs: float, comparator: Comparator, name: str
    ) -> None: ...
    @overload
    def __init__(
        self, lhs: Variable, rhs: float, comparator: Comparator, name: str
    ) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    @property
    def name(self) -> str | None: ...

class Constraints:
    @overload
    def add_constraint(self, constraint: Constraint): ...
    @overload
    def add_constraint(self, constraint: Constraint, name: str | None = ...): ...
    @overload
    def encode(self) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def encode(self, level: int | None = ...) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ..., level: int | None = ...) -> bytes: ...
    @overload
    def serialize(self) -> bytes: ...
    @overload
    def serialize(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def serialize(self, level: int | None = ...) -> bytes: ...
    @overload
    def serialize(
        self, compress: bool | None = ..., level: int | None = ...
    ) -> bytes: ...
    @staticmethod
    def decode(data: bytes) -> Expression: ...
    @staticmethod
    def deserialize(data: bytes) -> Expression: ...
    @overload
    def __iadd__(self, constraint: Constraint): ...
    @overload
    def __iadd__(self, constraint: tuple[Constraint, str]): ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __getitem__(self, item: int) -> Constraint: ...
