# This file is auto-generated.
# Do not edit manually.

from datetime import datetime, timedelta
from dimod import BinaryQuadraticModel
from dimod import ConstrainedQuadraticModel
from dimod import SampleSet
from enum import Enum
from numpy.typing import NDArray
from pathlib import Path
from pyscipopt import Model as SciModel
from qiskit.primitives import PrimitiveResult, PubResult
from qiskit_optimization import QuadraticProgram
from typing import Any
from typing import overload

from . import errors
from . import translator

class SamplesIterator:
    def __iter__(self) -> SamplesIterator: ...
    def __next__(self) -> Sample | None: ...

class SampleIterator:
    def __iter__(self) -> SampleIterator: ...
    def __next__(self) -> int | float | None: ...

class Samples:
    def __str__(self) -> str: ...
    @overload
    def __getitem__(self, item: int) -> Sample: ...
    @overload
    def __getitem__(self, item: tuple[int, int]) -> int | float: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> SamplesIterator: ...
    def tolist(self) -> list[list[int | float]]: ...

class Sample:
    def __str__(self) -> str: ...
    @overload
    def __getitem__(self, item: Variable) -> int | float: ...
    @overload
    def __getitem__(self, item: int) -> int | float: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> SampleIterator: ...

class Timing:
    @property
    def start(self) -> datetime: ...
    @property
    def end(self) -> datetime: ...
    @property
    def total(self) -> timedelta: ...
    @property
    def total_seconds(self) -> float: ...
    @property
    def qpu(self) -> float | None: ...
    @qpu.setter
    def qpu(self, value: float | None): ...
    def add_qpu(self, value: float): ...

class Timer:
    @staticmethod
    def start() -> Timer: ...
    def stop(self) -> Timing: ...

class ResultIterator:
    def __iter__(self) -> ResultIterator: ...
    def __next__(self) -> ResultView: ...

class Result:
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    @property
    def sample(self) -> Sample: ...
    @property
    def obj_value(self) -> float | None: ...
    @property
    def constraints(self) -> NDArray | None: ...
    @property
    def feasible(self) -> bool | None: ...

class ResultView:
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    @property
    def sample(self) -> Sample: ...
    @property
    def counts(self) -> int: ...
    @property
    def obj_value(self) -> float | None: ...
    @property
    def raw_energy(self) -> float | None: ...
    @property
    def constraints(self) -> NDArray | None: ...
    @property
    def feasible(self) -> bool | None: ...

class Solution:
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __iter__(self) -> ResultIterator: ...
    def __getitem__(self, item: int) -> ResultView: ...
    def __eq__(self, other: Solution) -> bool: ...  # type: ignore
    @property
    def results(self) -> ResultIterator: ...
    @property
    def samples(self) -> Samples: ...
    @property
    def obj_values(self) -> NDArray: ...
    @property
    def raw_energies(self) -> NDArray: ...
    @property
    def counts(self) -> NDArray: ...
    @property
    def runtime(self) -> Timing | None: ...
    @property
    def best_sample_idx(self) -> int | None: ...
    @overload
    def serialize(self) -> bytes: ...
    @overload
    def serialize(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def serialize(self, level: int | None = ...) -> bytes: ...
    @overload
    def serialize(
        self, compress: bool | None = ..., level: int | None = ...
    ) -> bytes: ...
    @overload
    def encode(self) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def encode(self, level: int | None = ...) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ..., level: int | None = ...) -> bytes: ...
    @staticmethod
    def deserialize(data: bytes) -> Solution: ...
    @staticmethod
    def decode(data: bytes) -> Solution: ...
    @staticmethod
    def build(
        component_types: list[Vtype],
        counts: list[int] | None = ...,
        binary_cols: list[list[int]] | None = ...,
        spin_cols: list[list[int]] | None = ...,
        int_cols: list[list[int]] | None = ...,
        real_cols: list[list[float]] | None = ...,
        raw_energies: list[float | None] | None = ...,
        timing: Timing | None = ...,
    ) -> Solution: ...

class Expression:
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, env: Environment): ...
    def get_offset(self) -> float: ...
    def get_linear(self, variable: Variable) -> float: ...
    def get_higher_order(self, variables: tuple[Variable, ...]) -> float: ...
    def get_quadratic(self, u: Variable, v: Variable) -> float: ...
    def num_variables(self) -> int: ...
    @overload
    def serialize(self) -> bytes: ...
    @overload
    def serialize(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def serialize(self, level: int | None = ...) -> bytes: ...
    @overload
    def serialize(
        self, compress: bool | None = ..., level: int | None = ...
    ) -> bytes: ...
    @overload
    def encode(self) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def encode(self, level: int | None = ...) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ..., level: int | None = ...) -> bytes: ...
    @staticmethod
    def deserialize(data: bytes) -> Expression: ...
    @staticmethod
    def decode(data: bytes) -> Expression: ...

    # addition
    @overload
    def __add__(self, other: Expression) -> Expression: ...
    @overload
    def __add__(self, other: Variable) -> Expression: ...
    @overload
    def __add__(self, other: int) -> Expression: ...
    @overload
    def __add__(self, other: float) -> Expression: ...
    @overload
    def __radd__(self, other: Expression) -> Expression: ...
    @overload
    def __radd__(self, other: Variable) -> Expression: ...
    @overload
    def __radd__(self, other: int) -> Expression: ...
    @overload
    def __radd__(self, other: float) -> Expression: ...
    # Instance addition
    @overload
    def __iadd__(self, other: Expression) -> Expression: ...
    @overload
    def __iadd__(self, other: Variable) -> Expression: ...
    @overload
    def __iadd__(self, other: int) -> Expression: ...
    @overload
    def __iadd__(self, other: float) -> Expression: ...
    # sub
    @overload
    def __sub__(self, other: Expression) -> Expression: ...
    @overload
    def __sub__(self, other: Variable) -> Expression: ...
    @overload
    def __sub__(self, other: int) -> Expression: ...
    @overload
    def __sub__(self, other: float) -> Expression: ...

    # Multiplication
    @overload
    def __mul__(self, other: Expression) -> Expression: ...
    @overload
    def __mul__(self, other: Variable) -> Expression: ...
    @overload
    def __mul__(self, other: int) -> Expression: ...
    @overload
    def __mul__(self, other: float) -> Expression: ...
    @overload
    def __rmul__(self, other: int) -> Expression: ...
    @overload
    def __rmul__(self, other: float) -> Expression: ...
    # Instance multiplication
    @overload
    def __imul__(self, other: Expression) -> Expression: ...
    @overload
    def __imul__(self, other: Variable) -> Expression: ...
    @overload
    def __imul__(self, other: int) -> Expression: ...
    @overload
    def __imul__(self, other: float) -> Expression: ...
    # pow
    def __pow__(self, other: int) -> Expression: ...

    # Constraint creation
    @overload  # type: ignore
    def __eq__(self, value: Expression) -> bool: ...  # type: ignore
    @overload
    def __eq__(self, value: int) -> Constraint: ...  # type: ignore
    @overload
    def __eq__(self, value: float) -> Constraint: ...  # type: ignore
    @overload
    def __le__(self, other: int) -> Constraint: ...
    @overload
    def __le__(self, other: float) -> Constraint: ...
    @overload
    def __ge__(self, other: int) -> Constraint: ...
    @overload
    def __ge__(self, other: float) -> Constraint: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Environment:
    def __init__(self) -> None: ...
    def __enter__(self) -> Any: ...
    def __exit__(self, exc_type, exc_value, exc_traceback) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def get_variable(self, name: str) -> Variable: ...
    @overload
    def serialize(self) -> bytes: ...
    @overload
    def serialize(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def serialize(self, level: int | None = ...) -> bytes: ...
    @overload
    def serialize(
        self, compress: bool | None = ..., level: int | None = ...
    ) -> bytes: ...
    @overload
    def encode(self) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def encode(self, level: int | None = ...) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ..., level: int | None = ...) -> bytes: ...
    @staticmethod
    def deserialize(data: bytes) -> Environment: ...
    @staticmethod
    def decode(data: bytes) -> Environment: ...

class Vtype(Enum):
    Real = ...
    Integer = ...
    Binary = ...
    Spin = ...

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Bounds:
    @overload
    def __init__(self, lower: float, upper: float) -> None: ...
    @overload
    def __init__(self, lower: float) -> None: ...
    @overload
    def __init__(self, upper: float) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Variable:
    def __init__(
        self,
        name: str,
        env: Environment | None = ...,
        vtype: Vtype | None = ...,
        bounds: Bounds | None = ...,
    ) -> None: ...
    @overload
    def __new__(
        cls, name: str, vtype: Vtype | None = ..., bounds: Bounds | None = ...
    ) -> Variable: ...
    @overload
    def __new__(
        cls,
        name: str,
        env: Environment,
        vtype: Vtype | None = ...,
        bounds: Bounds | None = ...,
    ) -> Variable: ...

    # addition
    @overload
    def __add__(self, other: Variable) -> Expression: ...
    @overload
    def __add__(self, other: Expression) -> Expression: ...
    @overload
    def __add__(self, other: int) -> Expression: ...
    @overload
    def __add__(self, other: float) -> Expression: ...
    @overload
    def __radd__(self, other: int) -> Expression: ...
    @overload
    def __radd__(self, other: float) -> Expression: ...
    # subtraction
    @overload
    def __sub__(self, other: Expression) -> Expression: ...
    @overload
    def __sub__(self, other: Variable) -> Expression: ...
    @overload
    def __sub__(self, other: int) -> Expression: ...
    @overload
    def __sub__(self, other: float) -> Expression: ...
    @overload
    def __rsub__(self, other: int) -> Expression: ...
    @overload
    def __rsub__(self, other: float) -> Expression: ...
    # multiplication
    @overload
    def __mul__(self, other: Expression) -> Expression: ...
    @overload
    def __mul__(self, other: Variable) -> Expression: ...
    @overload
    def __mul__(self, other: int) -> Expression: ...
    @overload
    def __mul__(self, other: float) -> Expression: ...
    @overload
    def __rmul__(self, other: int) -> Expression: ...
    @overload
    def __rmul__(self, other: float) -> Expression: ...
    # pow
    def __pow__(self, other: int) -> Expression: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, value: float) -> Constraint: ...  # type: ignore
    def __le__(self, value: float) -> Constraint: ...
    def __ge__(self, value: float) -> Constraint: ...
    @property
    def name(self) -> str: ...

class Comparator(Enum):
    Eq = ...
    Le = ...
    Ge = ...

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Constraint:
    @overload
    def __init__(self, lhs: Expression, rhs: float, comparator: Comparator) -> None: ...
    @overload
    def __init__(self, lhs: Variable, rhs: float, comparator: Comparator) -> None: ...
    @overload
    def __init__(
        self, lhs: Expression, rhs: float, comparator: Comparator, name: str
    ) -> None: ...
    @overload
    def __init__(
        self, lhs: Variable, rhs: float, comparator: Comparator, name: str
    ) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    @property
    def name(self) -> str | None: ...

class Constraints:
    @overload
    def add_constraint(self, constraint: Constraint): ...
    @overload
    def add_constraint(self, constraint: Constraint, name: str | None = ...): ...
    @overload
    def encode(self) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def encode(self, level: int | None = ...) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ..., level: int | None = ...) -> bytes: ...
    @overload
    def serialize(self) -> bytes: ...
    @overload
    def serialize(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def serialize(self, level: int | None = ...) -> bytes: ...
    @overload
    def serialize(
        self, compress: bool | None = ..., level: int | None = ...
    ) -> bytes: ...
    @staticmethod
    def decode(data: bytes) -> Expression: ...
    @staticmethod
    def deserialize(data: bytes) -> Expression: ...
    @overload
    def __iadd__(self, constraint: Constraint): ...
    @overload
    def __iadd__(self, constraint: tuple[Constraint, str]): ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __getitem__(self, item: int) -> Constraint: ...

class Sense(Enum):
    Min = ...
    Max = ...

class Model:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, name: str) -> None: ...
    @overload
    def __init__(self, env: Environment) -> None: ...
    @overload
    def __init__(
        self,
        name: str | None = ...,
        env: Environment | None = ...,
    ) -> None: ...
    def set_sense(self, sense: Sense) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def objective(self) -> Expression: ...
    @objective.setter
    def objective(self, value: Expression): ...
    @property
    def constraints(self) -> Constraints: ...
    @constraints.setter
    def constraints(self, value: Constraints): ...
    @property
    def environment(self) -> Environment: ...
    @overload
    def add_constraint(self, constraint: Constraint): ...
    @overload
    def add_constraint(self, constraint: Constraint, name: str | None = ...): ...
    def num_constraints(self) -> int: ...
    def evaluate(self, solution: Solution) -> Solution: ...
    def evaluate_sample(self, sample: Sample) -> Result: ...
    @overload
    def serialize(self) -> bytes: ...
    @overload
    def serialize(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def serialize(self, level: int | None = ...) -> bytes: ...
    @overload
    def serialize(
        self, compress: bool | None = ..., level: int | None = ...
    ) -> bytes: ...
    @overload
    def encode(self) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def encode(self, level: int | None = ...) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ..., level: int | None = ...) -> bytes: ...
    @staticmethod
    def deserialize(data: bytes) -> Model: ...
    @staticmethod
    def decode(data: bytes) -> Model: ...

class NumpyTranslator:
    @staticmethod
    def to_aq(
        result: NDArray,
        energies: NDArray,
        timing: Timing | None = ...,
        env: Environment | None = ...,
    ) -> Solution: ...

class ZibTranslator:
    @staticmethod
    def to_aq(
        model: SciModel,
        timing: Timing | None = ...,
        env: Environment | None = ...,
    ) -> Solution: ...

class DwaveTranslator:
    @staticmethod
    def to_aq(
        sample_set: SampleSet,
        timing: Timing | None = ...,
        env: Environment | None = ...,
    ) -> Solution: ...

class CqmTranslator:
    @staticmethod
    def to_aq(cqm: ConstrainedQuadraticModel) -> Model: ...
    @staticmethod
    def from_aq(model: Model) -> ConstrainedQuadraticModel: ...

class Qubo:
    @property
    def offset(self) -> float: ...
    @property
    def matrix(self) -> NDArray: ...
    @property
    def variable_names(self) -> list[str]: ...
    @property
    def name(self) -> str: ...
    @property
    def vtype(self) -> Vtype: ...

class QuboTranslator:
    @staticmethod
    def to_aq(
        qubo: NDArray,
        offset: float | None = ...,
        variable_names: list[str] | None = ...,
        name: str | None = ...,
        vtype: Vtype | None = ...,
    ) -> Model: ...
    @staticmethod
    def from_aq(model: Model) -> Qubo: ...

class BqmTranslator:
    @staticmethod
    def to_aq(bqm: BinaryQuadraticModel, name: str | None = None) -> Model: ...
    @staticmethod
    def from_aq(model: Model) -> BinaryQuadraticModel: ...

class AwsTranslator:
    @staticmethod
    def to_aq(
        result: dict[str, Any],
        timing: Timing | None = ...,
        env: Environment | None = ...,
    ) -> Solution: ...

class QctrlTranslator:
    @overload
    @staticmethod
    def to_aq(result: dict[str, Any]) -> Solution: ...
    @overload
    @staticmethod
    def to_aq(
        result: dict[str, Any],
        timing: Timing | None = ...,
    ) -> Solution: ...
    @overload
    @staticmethod
    def to_aq(
        result: dict[str, Any],
        timing: Timing | None = ...,
        env: Environment | None = ...,
    ) -> Solution: ...

class IbmTranslator:
    @overload
    @staticmethod
    def to_aq(
        result: PrimitiveResult[PubResult], quadratic_program: QuadraticProgram
    ) -> Solution: ...
    @overload
    @staticmethod
    def to_aq(
        result: PrimitiveResult[PubResult],
        quadratic_program: QuadraticProgram,
        timing: Timing | None = ...,
    ) -> Solution: ...
    @overload
    @staticmethod
    def to_aq(
        result: PrimitiveResult[PubResult],
        quadratic_program: QuadraticProgram,
        timing: Timing | None = ...,
        env: Environment | None = ...,
    ) -> Solution: ...

class LpTranslator:
    @overload
    @staticmethod
    def to_aq(file: Path) -> Model: ...
    @overload
    @staticmethod
    def to_aq(file: str) -> Model: ...
    @overload
    @staticmethod
    def from_aq(model: Model) -> str: ...
    @overload
    @staticmethod
    def from_aq(model: Model, file: Path) -> None: ...

class VariableOutOfRangeError(Exception):
    def __str__(self) -> str: ...

class VariableExistsError(Exception):
    def __str__(self) -> str: ...

class VariableNotExistingError(Exception):
    def __str__(self) -> str: ...

class VariablesFromDifferentEnvsError(Exception):
    def __str__(self) -> str: ...

class DifferentEnvsError(Exception):
    def __str__(self) -> str: ...

class NoActiveEnvironmentFoundError(Exception):
    def __str__(self) -> str: ...

class MultipleActiveEnvironmentsError(Exception):
    def __str__(self) -> str: ...

class DecodeError(Exception):
    def __str__(self) -> str: ...

class ModelVtypeError(Exception):
    def __str__(self) -> str: ...

class SolutionCreationError(Exception):
    def __str__(self) -> str: ...

class IllegalConstraintNameError(Exception):
    def __str__(self) -> str: ...

class TranslationError(Exception):
    def __str__(self) -> str: ...

class ModelNotQuadraticError(TranslationError):
    def __str__(self) -> str: ...

class ModelNotUnconstrainedError(TranslationError):
    def __str__(self) -> str: ...

__all__ = [
    "AwsTranslator",
    "Bounds",
    "BqmTranslator",
    "Comparator",
    "Constraint",
    "Constraints",
    "CqmTranslator",
    "DecodeError",
    "DifferentEnvsError",
    "DwaveTranslator",
    "Environment",
    "Expression",
    "IbmTranslator",
    "IllegalConstraintNameError",
    "LpTranslator",
    "Model",
    "ModelNotQuadraticError",
    "ModelNotUnconstrainedError",
    "ModelVtypeError",
    "MultipleActiveEnvironmentsError",
    "NoActiveEnvironmentFoundError",
    "NumpyTranslator",
    "QctrlTranslator",
    "Qubo",
    "QuboTranslator",
    "Result",
    "ResultIterator",
    "ResultView",
    "Sample",
    "SampleIterator",
    "Samples",
    "SamplesIterator",
    "Sense",
    "Solution",
    "SolutionCreationError",
    "Timer",
    "Timing",
    "TranslationError",
    "Variable",
    "VariableExistsError",
    "VariableNotExistingError",
    "VariableOutOfRangeError",
    "VariablesFromDifferentEnvsError",
    "Vtype",
    "ZibTranslator",
    "errors",
    "translator",
]
