from typing import Any
from typing import overload
from aqmodels._expression import Expression

class Environment:
    def __init__(self) -> None: ...
    def __enter__(self) -> Any: ...
    def __exit__(self, exc_type, exc_value, exc_traceback) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    @overload
    def serialize(self) -> bytes: ...
    @overload
    def serialize(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def serialize(self, level: int | None = ...) -> bytes: ...
    @overload
    def serialize(
        self, compress: bool | None = ..., level: int | None = ...
    ) -> bytes: ...
    @overload
    def encode(self) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def encode(self, level: int | None = ...) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ..., level: int | None = ...) -> bytes: ...
    @staticmethod
    def deserialize(data: bytes) -> Expression: ...
    @staticmethod
    def decode(data: bytes) -> Expression: ...
