from typing import overload
from aqmodels import Variable
from aqmodels import Environment
from aqmodels import Constraint

class Expression:
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, env: Environment): ...
    def get_offset(self) -> float: ...
    def get_linear(self, variable: Variable) -> float: ...
    def get_higher_order(self, variables: tuple[Variable, ...]) -> float: ...
    def get_quadratic(self, u: Variable, v: Variable) -> float: ...
    def num_variables(self) -> int: ...
    @overload
    def serialize(self) -> bytes: ...
    @overload
    def serialize(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def serialize(self, level: int | None = ...) -> bytes: ...
    @overload
    def serialize(
        self, compress: bool | None = ..., level: int | None = ...
    ) -> bytes: ...
    @overload
    def encode(self) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def encode(self, level: int | None = ...) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ..., level: int | None = ...) -> bytes: ...
    @staticmethod
    def deserialize(data: bytes) -> Expression: ...
    @staticmethod
    def decode(data: bytes) -> Expression: ...

    # addition
    @overload
    def __add__(self, other: Expression) -> Expression: ...
    @overload
    def __add__(self, other: Variable) -> Expression: ...
    @overload
    def __add__(self, other: int) -> Expression: ...
    @overload
    def __add__(self, other: float) -> Expression: ...
    @overload
    def __radd__(self, other: Expression) -> Expression: ...
    @overload
    def __radd__(self, other: Variable) -> Expression: ...
    @overload
    def __radd__(self, other: int) -> Expression: ...
    @overload
    def __radd__(self, other: float) -> Expression: ...
    # Instance addition
    @overload
    def __iadd__(self, other: Expression) -> Expression: ...
    @overload
    def __iadd__(self, other: Variable) -> Expression: ...
    @overload
    def __iadd__(self, other: int) -> Expression: ...
    @overload
    def __iadd__(self, other: float) -> Expression: ...
    # sub
    @overload
    def __sub__(self, other: Expression) -> Expression: ...
    @overload
    def __sub__(self, other: Variable) -> Expression: ...
    @overload
    def __sub__(self, other: int) -> Expression: ...
    @overload
    def __sub__(self, other: float) -> Expression: ...

    # Multiplication
    @overload
    def __mul__(self, other: Expression) -> Expression: ...
    @overload
    def __mul__(self, other: Variable) -> Expression: ...
    @overload
    def __mul__(self, other: int) -> Expression: ...
    @overload
    def __mul__(self, other: float) -> Expression: ...
    @overload
    def __rmul__(self, other: int) -> Expression: ...
    @overload
    def __rmul__(self, other: float) -> Expression: ...
    # Instance multiplication
    @overload
    def __imul__(self, other: Expression) -> Expression: ...
    @overload
    def __imul__(self, other: Variable) -> Expression: ...
    @overload
    def __imul__(self, other: int) -> Expression: ...
    @overload
    def __imul__(self, other: float) -> Expression: ...
    # pow
    def __pow__(self, other: int) -> Expression: ...

    # Constraint creation
    @overload  # type: ignore
    def __eq__(self, value: Expression) -> bool: ...  # type: ignore
    @overload
    def __eq__(self, value: int) -> Constraint: ...  # type: ignore
    @overload
    def __eq__(self, value: float) -> Constraint: ...  # type: ignore
    @overload
    def __le__(self, other: int) -> Constraint: ...
    @overload
    def __le__(self, other: float) -> Constraint: ...
    @overload
    def __ge__(self, other: int) -> Constraint: ...
    @overload
    def __ge__(self, other: float) -> Constraint: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
