from enum import Enum
from typing import overload

from aqmodels import Constraint
from aqmodels import Constraints
from aqmodels import Environment
from aqmodels import Expression
from aqmodels import Result
from aqmodels import Sample
from aqmodels import Solution

class Sense(Enum):
    Min = ...
    Max = ...

class Model:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, name: str) -> None: ...
    @overload
    # TODO (0.1.2): don't we need a default for env? Not too familiar with pyi overloads tbh
    def __init__(self, /, *, env: Environment) -> None: ...
    @overload
    def __init__(
        self,
        name: str | None = ...,
        env: Environment | None = ...,
    ) -> None: ...
    def set_sense(self, sense: Sense) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def objective(self) -> Expression: ...
    @property
    def sense(self) -> Sense: ...
    @objective.setter
    def objective(self, value: Expression): ...
    @property
    def constraints(self) -> Constraints: ...
    @constraints.setter
    def constraints(self, value: Constraints): ...
    @property
    def environment(self) -> Environment: ...
    @overload
    def add_constraint(self, constraint: Constraint): ...
    @overload
    def add_constraint(self, constraint: Constraint, name: str | None = ...): ...
    @overload
    def set_objective(self, expression: Expression): ...
    @overload
    def set_objective(self, expression: Expression, sense: Sense | None = ...): ...
    def num_constraints(self) -> int: ...
    def evaluate(self, solution: Solution) -> Solution: ...
    def evaluate_sample(self, sample: Sample) -> Result: ...
    @overload
    def serialize(self) -> bytes: ...
    @overload
    def serialize(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def serialize(self, level: int | None = ...) -> bytes: ...
    @overload
    def serialize(
        self, compress: bool | None = ..., level: int | None = ...
    ) -> bytes: ...
    @overload
    def encode(self) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def encode(self, level: int | None = ...) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ..., level: int | None = ...) -> bytes: ...
    @staticmethod
    def deserialize(data: bytes) -> Model: ...
    @staticmethod
    def decode(data: bytes) -> Model: ...
    def __eq__(self, other: Model) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
