from typing import overload
from aqmodels._expression import Expression
from aqmodels._environment import Environment
from aqmodels._constraints import Constraints

class Model:
    def __init__(
        self,
        env: Environment | None = ...,
        name: str | None = ...,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def objective(self) -> Expression: ...
    @objective.setter
    def objective(self, value: Expression): ...
    @property
    def constraints(self) -> Constraints: ...
    @constraints.setter
    def constraints(self, value: Constraints): ...
    @property
    def environment(self) -> Environment: ...
    def num_constraints(self) -> int: ...
    @overload
    def serialize(self) -> bytes: ...
    @overload
    def serialize(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def serialize(self, level: int | None = ...) -> bytes: ...
    @overload
    def serialize(
        self, compress: bool | None = ..., level: int | None = ...
    ) -> bytes: ...
    @overload
    def encode(self) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def encode(self, level: int | None = ...) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ..., level: int | None = ...) -> bytes: ...
    @staticmethod
    def deserialize(data: bytes) -> Expression: ...
    @staticmethod
    def decode(data: bytes) -> Expression: ...
