from typing import overload

from aqmodels import Variable

class SamplesIterator:
    def __iter__(self) -> SamplesIterator: ...
    def __next__(self) -> Sample: ...

class SampleIterator:
    def __iter__(self) -> SampleIterator: ...
    def __next__(self) -> int | float: ...

class Samples:
    def __str__(self) -> str: ...
    @overload
    def __getitem__(self, item: int) -> Sample: ...
    @overload
    def __getitem__(self, item: tuple[int, int]) -> int | float: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> SamplesIterator: ...
    def tolist(self) -> list[list[int | float]]: ...

class Sample:
    def __str__(self) -> str: ...
    @overload
    def __getitem__(self, item: Variable) -> int | float: ...
    @overload
    def __getitem__(self, item: int) -> int | float: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> SampleIterator: ...
