from datetime import datetime, timedelta

from numpy.typing import NDArray
from typing_extensions import overload


class ResultIterator:
    def __iter__(self) -> ResultIterator: ...

    def __next__(self) -> ResultView: ...


class SamplesIterator:
    def __iter__(self) -> SamplesIterator: ...

    def __next__(self) -> Sample | None: ...


class SampleIterator:
    def __iter__(self) -> SampleIterator: ...

    def __next__(self) -> int | float | None: ...


class Samples:
    def __str__(self) -> str: ...

    @overload
    def __getitem__(self, item: int) -> Sample: ...

    @overload
    def __getitem__(self, item: tuple[int, int]) -> int | float: ...

    def __len__(self) -> int: ...

    def __iter__(self) -> SamplesIterator: ...

    def tolist(self) -> list[list[int | float]]: ...


class Sample:
    def __str__(self) -> str: ...

    def __getitem__(self, item: int) -> int | float: ...

    def __len__(self) -> int: ...

    def __iter__(self) -> SampleIterator: ...


class Result:
    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    @property
    def sample(self) -> Sample: ...

    @property
    def obj_value(self) -> float | None: ...

    @property
    def constraints(self) -> NDArray | None: ...

    @property
    def feasible(self) -> bool | None: ...


class ResultView:
    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    @property
    def sample(self) -> Sample: ...

    @property
    def num_occurrences(self) -> int: ...

    @property
    def obj_value(self) -> float | None: ...

    @property
    def constraints(self) -> NDArray | None: ...

    @property
    def feasible(self) -> bool | None: ...


class Solution:
    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    def __iter__(self) -> ResultIterator: ...

    def __getitem__(self, item: int) -> ResultView: ...

    @property
    def results(self) -> ResultIterator: ...

    @property
    def samples(self) -> Samples: ...

    @property
    def obj_values(self) -> NDArray: ...

    @property
    def num_occurrences(self) -> NDArray: ...

    @property
    def runtime(self) -> Timing | None: ...

    @property
    def best_sample_idx(self) -> int | None: ...


class Timing:
    @property
    def start(self) -> datetime: ...

    @property
    def end(self) -> datetime: ...

    @property
    def total(self) -> timedelta: ...

    @property
    def total_seconds(self) -> float: ...

    @property
    def qpu(self) -> float | None: ...

    @qpu.setter
    def qpu(self, value: float | None): ...

    def add_qpu(self, value: float): ...


class Timer:
    @staticmethod
    def start(cls) -> Timer: ...

    def stop(self) -> Timing: ...
