from datetime import datetime, timedelta

from numpy.typing import NDArray


class Sample:
    def __iter__(self) -> Sample: ...

    def __next__(self) -> int | float | None: ...


class ResultView:
    @property
    def sample(self) -> Sample: ...

    @property
    def num_occurrences(self) -> int: ...

    @property
    def obj_value(self) -> float | None: ...

    @property
    def constraints(self) -> NDArray | None: ...

    @property
    def feasible(self) -> bool | None: ...


class Results:
    def __iter__(self) -> Results: ...

    def __next__(self) -> ResultView: ...


class Solution:
    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    def __iter__(self) -> Results: ...

    @property
    def results(self) -> Results: ...

    @property
    def samples(self) -> NDArray: ...

    @property
    def obj_values(self) -> NDArray: ...

    @property
    def num_occurrences(self) -> NDArray: ...

    @property
    def runtime(self) -> Timing | None: ...

    @property
    def best_sample_idx(self) -> int | None: ...


class Timing:
    @property
    def start(self) -> datetime: ...

    @property
    def end(self) -> datetime: ...

    @property
    def total(self) -> timedelta: ...

    @property
    def total_seconds(self) -> float: ...

    @property
    def qpu(self) -> float | None: ...

    @qpu.setter
    def qpu(self, value: float | None): ...

    def add_qpu(self, value: float): ...


class Timer:
    @staticmethod
    def start(cls) -> Timer: ...

    def stop(self) -> Timing: ...
