from enum import Enum
from typing import overload
from aqmodels import Constraint
from aqmodels._environment import Environment
from aqmodels._expression import Expression

class Vtype(Enum):
    Real = ...
    Integer = ...
    Binary = ...
    Spin = ...

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Bounds:
    @overload
    def __init__(self, lower: float, upper: float) -> None: ...
    @overload
    def __init__(self, lower: float) -> None: ...
    @overload
    def __init__(self, upper: float) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Variable:
    def __init__(
        self,
        name: str,
        env: Environment | None = ...,
        vtype: Vtype | None = ...,
        bounds: Bounds | None = ...,
    ) -> None: ...
    @overload
    def __new__(
        cls, name: str, vtype: Vtype | None = ..., bounds: Bounds | None = ...
    ) -> Variable: ...
    @overload
    def __new__(
        cls,
        name: str,
        env: Environment,
        vtype: Vtype | None = ...,
        bounds: Bounds | None = ...,
    ) -> Variable: ...

    # addition
    @overload
    def __add__(self, other: Variable) -> Expression: ...
    @overload
    def __add__(self, other: Expression) -> Expression: ...
    @overload
    def __add__(self, other: int) -> Expression: ...
    @overload
    def __add__(self, other: float) -> Expression: ...
    @overload
    def __radd__(self, other: int) -> Expression: ...
    @overload
    def __radd__(self, other: float) -> Expression: ...
    # subtraction
    @overload
    def __sub__(self, other: Variable) -> Expression: ...
    @overload
    def __sub__(self, other: int) -> Expression: ...
    @overload
    def __sub__(self, other: float) -> Expression: ...
    @overload
    def __rsub__(self, other: int) -> Expression: ...
    @overload
    def __rsub__(self, other: float) -> Expression: ...
    # multiplication
    @overload
    def __mul__(self, other: Expression) -> Expression: ...
    @overload
    def __mul__(self, other: Variable) -> Expression: ...
    @overload
    def __mul__(self, other: int) -> Expression: ...
    @overload
    def __mul__(self, other: float) -> Expression: ...
    @overload
    def __rmul__(self, other: int) -> Expression: ...
    @overload
    def __rmul__(self, other: float) -> Expression: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, value: float) -> Constraint: ...  # type: ignore
    def __le__(self, value: float) -> Constraint: ...
    def __ge__(self, value: float) -> Constraint: ...
