from enum import Enum
from typing import overload

from aqmodels import Constraint
from aqmodels import Environment
from aqmodels import Expression

class Vtype(Enum):
    Real = ...
    Integer = ...
    Binary = ...
    Spin = ...

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Bounds:
    @overload
    def __init__(self, lower: float, upper: float) -> None: ...
    @overload
    def __init__(self, lower: float) -> None: ...
    @overload
    # TODO (0.1.2): we might need a default here?
    def __init__(self, upper: float) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Variable:
    def __init__(
        self,
        name: str,
        env: Environment | None = ...,
        vtype: Vtype | None = ...,
        bounds: Bounds | None = ...,
    ) -> None: ...
    @overload
    def __new__(
        cls, name: str, vtype: Vtype | None = ..., bounds: Bounds | None = ...
    ) -> Variable: ...
    @overload
    def __new__(
        cls,
        name: str,
        env: Environment,
        vtype: Vtype | None = ...,
        bounds: Bounds | None = ...,
    ) -> Variable: ...
    def __hash__(self) -> int: ...

    # addition
    @overload
    def __add__(self, other: Variable) -> Expression: ...
    @overload
    def __add__(self, other: Expression) -> Expression: ...
    @overload
    def __add__(self, other: int) -> Expression: ...
    @overload
    def __add__(self, other: float) -> Expression: ...
    @overload
    def __radd__(self, other: Variable) -> Expression: ...
    @overload
    def __radd__(self, other: Expression) -> Expression: ...
    @overload
    def __radd__(self, other: int) -> Expression: ...
    @overload
    def __radd__(self, other: float) -> Expression: ...

    # subtraction
    @overload
    def __sub__(self, other: Expression) -> Expression: ...
    @overload
    def __sub__(self, other: Variable) -> Expression: ...
    @overload
    def __sub__(self, other: int) -> Expression: ...
    @overload
    def __sub__(self, other: float) -> Expression: ...
    @overload
    def __rsub__(self, other: int) -> Expression: ...
    @overload
    def __rsub__(self, other: float) -> Expression: ...

    # multiplication
    @overload
    def __mul__(self, other: Expression) -> Expression: ...
    @overload
    def __mul__(self, other: Variable) -> Expression: ...
    @overload
    def __mul__(self, other: int) -> Expression: ...
    @overload
    def __mul__(self, other: float) -> Expression: ...
    @overload
    def __rmul__(self, other: Expression) -> Expression: ...
    @overload
    def __rmul__(self, other: Variable) -> Expression: ...
    @overload
    def __rmul__(self, other: int) -> Expression: ...
    @overload
    def __rmul__(self, other: float) -> Expression: ...

    # pow
    def __pow__(self, other: int) -> Expression: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    @overload
    def __eq__(self, rhs: Expression) -> Constraint: ...  # type: ignore
    @overload
    def __eq__(self, rhs: Variable) -> Constraint: ...  # type: ignore
    @overload
    def __eq__(self, rhs: float) -> Constraint: ...  # type: ignore
    @overload
    def __eq__(self, rhs: int) -> Constraint: ...  # type: ignore
    @overload
    def __le__(self, rhs: Expression) -> Constraint: ...
    @overload
    def __le__(self, rhs: Variable) -> Constraint: ...
    @overload
    def __le__(self, rhs: int) -> Constraint: ...
    @overload
    def __le__(self, rhs: float) -> Constraint: ...
    @overload
    def __ge__(self, rhs: Expression) -> Constraint: ...
    @overload
    def __ge__(self, rhs: Variable) -> Constraint: ...
    @overload
    def __ge__(self, rhs: int) -> Constraint: ...
    @overload
    def __ge__(self, rhs: float) -> Constraint: ...
    def __neg__(self) -> Expression: ...
    @property
    def name(self) -> str: ...
