class VariableOutOfRangeException(Exception):
    def __str__(self) -> str: ...

class VariableExistsException(Exception):
    def __str__(self) -> str: ...

class VariablesFromDifferentEnvsException(Exception):
    def __str__(self) -> str: ...

class DifferentEnvsException(Exception):
    def __str__(self) -> str: ...

class NoActiveEnvironmentFoundException(Exception):
    def __str__(self) -> str: ...

class MultipleActiveEnvironmentsException(Exception):
    def __str__(self) -> str: ...

class DecodeException(Exception):
    def __str__(self) -> str: ...

class ModelNotQuadraticException(Exception):
    def __str__(self) -> str: ...

class ModelNotUnconstrainedException(Exception):
    def __str__(self) -> str: ...
