from enum import Enum
from typing import Any, Tuple, overload
from numpy.typing import NDArray

class Vtype(Enum):
    Real = ...
    Integer = ...
    Binary = ...
    Spin = ...

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Comparator(Enum):
    Eq = ...
    Leq = ...
    Geq = ...

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Bounds:
    @overload
    def __init__(self, lower: float, upper: float) -> None: ...
    @overload
    def __init__(self, lower: float) -> None: ...
    @overload
    def __init__(self, upper: float) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Constraint:
    def __init__(self, lhs: Expression, rhs: float, comparator: Comparator) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Constraints:
    def __iadd__(self, constraint: Constraint): ...
    def add_constraint(self, constraint: Constraint): ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    @overload
    def serialize(self) -> bytes: ...
    @overload
    def serialize(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def serialize(self, level: int | None = ...) -> bytes: ...
    @overload
    def serialize(
        self, compress: bool | None = ..., level: int | None = ...
    ) -> bytes: ...
    @overload
    def encode(self) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def encode(self, level: int | None = ...) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ..., level: int | None = ...) -> bytes: ...
    @staticmethod
    def deserialize(data: bytes) -> Expression: ...
    @staticmethod
    def decode(data: bytes) -> Expression: ...

class Expression:
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, env: Environment): ...
    def get_offset(self) -> float: ...
    def get_linear(self, variable: Variable) -> float: ...
    def get_higher_order(self, variables: Tuple[Variable, ...]) -> float: ...
    def get_quadratic(self, u: Variable, v: Variable) -> float: ...
    def num_variables(self) -> int: ...
    @overload
    def serialize(self) -> bytes: ...
    @overload
    def serialize(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def serialize(self, level: int | None = ...) -> bytes: ...
    @overload
    def serialize(
        self, compress: bool | None = ..., level: int | None = ...
    ) -> bytes: ...
    @overload
    def encode(self) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def encode(self, level: int | None = ...) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ..., level: int | None = ...) -> bytes: ...
    @staticmethod
    def deserialize(data: bytes) -> Expression: ...
    @staticmethod
    def decode(data: bytes) -> Expression: ...

    # addition
    @overload
    def __add__(self, other: Expression) -> Expression: ...
    @overload
    def __add__(self, other: Variable) -> Expression: ...
    @overload
    def __add__(self, other: int) -> Expression: ...
    @overload
    def __add__(self, other: float) -> Expression: ...
    @overload
    def __radd__(self, other: Expression) -> Expression: ...
    @overload
    def __radd__(self, other: Variable) -> Expression: ...
    @overload
    def __radd__(self, other: int) -> Expression: ...
    @overload
    def __radd__(self, other: float) -> Expression: ...
    # Instance addition
    @overload
    def __iadd__(self, other: Expression) -> Expression: ...
    @overload
    def __iadd__(self, other: Variable) -> Expression: ...
    @overload
    def __iadd__(self, other: int) -> Expression: ...
    @overload
    def __iadd__(self, other: float) -> Expression: ...

    # Multiplication
    @overload
    def __mul__(self, other: Expression) -> Expression: ...
    @overload
    def __mul__(self, other: Variable) -> Expression: ...
    @overload
    def __mul__(self, other: int) -> Expression: ...
    @overload
    def __mul__(self, other: float) -> Expression: ...
    @overload
    def __rmul__(self, other: int) -> Expression: ...
    @overload
    def __rmul__(self, other: float) -> Expression: ...
    # Instance multiplication
    @overload
    def __imul__(self, other: Expression) -> Expression: ...
    @overload
    def __imul__(self, other: Variable) -> Expression: ...
    @overload
    def __imul__(self, other: int) -> Expression: ...
    @overload
    def __imul__(self, other: float) -> Expression: ...

    # Constraint creation
    @overload  # type: ignore
    def __eq__(self, value: Expression) -> bool: ...  # type: ignore
    @overload
    def __eq__(self, value: int) -> Constraint: ...  # type: ignore
    @overload
    def __eq__(self, value: float) -> Constraint: ...  # type: ignore
    @overload
    def __le__(self, other: int) -> Constraint: ...
    @overload
    def __le__(self, other: float) -> Constraint: ...
    @overload
    def __ge__(self, other: int) -> Constraint: ...
    @overload
    def __ge__(self, other: float) -> Constraint: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Variable:
    def __init__(
        self,
        name: str,
        env: Environment | None = ...,
        vtype: Vtype | None = ...,
        bounds: Bounds | None = ...,
    ) -> None: ...
    @overload
    def __new__(
        cls, name: str, vtype: Vtype | None = ..., bounds: Bounds | None = ...
    ) -> Variable: ...
    @overload
    def __new__(
        cls,
        name: str,
        env: Environment,
        vtype: Vtype | None = ...,
        bounds: Bounds | None = ...,
    ) -> Variable: ...

    # addition
    @overload
    def __add__(self, other: Variable) -> Expression: ...
    @overload
    def __add__(self, other: Expression) -> Expression: ...
    @overload
    def __add__(self, other: int) -> Expression: ...
    @overload
    def __add__(self, other: float) -> Expression: ...
    @overload
    def __radd__(self, other: int) -> Expression: ...
    @overload
    def __radd__(self, other: float) -> Expression: ...
    # subtraction
    @overload
    def __sub__(self, other: Variable) -> Expression: ...
    @overload
    def __sub__(self, other: int) -> Expression: ...
    @overload
    def __sub__(self, other: float) -> Expression: ...
    @overload
    def __rsub__(self, other: int) -> Expression: ...
    @overload
    def __rsub__(self, other: float) -> Expression: ...
    # multiplication
    @overload
    def __mul__(self, other: Expression) -> Expression: ...
    @overload
    def __mul__(self, other: Variable) -> Expression: ...
    @overload
    def __mul__(self, other: int) -> Expression: ...
    @overload
    def __mul__(self, other: float) -> Expression: ...
    @overload
    def __rmul__(self, other: int) -> Expression: ...
    @overload
    def __rmul__(self, other: float) -> Expression: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Environment:
    def __init__(self) -> None: ...
    def __enter__(self) -> Any: ...
    def __exit__(self, exc_type, exc_value, exc_traceback) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    @overload
    def serialize(self) -> bytes: ...
    @overload
    def serialize(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def serialize(self, level: int | None = ...) -> bytes: ...
    @overload
    def serialize(
        self, compress: bool | None = ..., level: int | None = ...
    ) -> bytes: ...
    @overload
    def encode(self) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def encode(self, level: int | None = ...) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ..., level: int | None = ...) -> bytes: ...
    @staticmethod
    def deserialize(data: bytes) -> Expression: ...
    @staticmethod
    def decode(data: bytes) -> Expression: ...

class Model:
    def __init__(
        self,
        env: Environment | None = ...,
        name: str | None = ...,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def objective(self) -> Expression: ...
    @objective.setter
    def objective(self, value: Expression): ...
    @property
    def constraints(self) -> Constraints: ...
    @constraints.setter
    def constraints(self, value: Constraints): ...
    @property
    def environment(self) -> Environment: ...
    def num_constraints(self) -> int: ...
    @overload
    def serialize(self) -> bytes: ...
    @overload
    def serialize(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def serialize(self, level: int | None = ...) -> bytes: ...
    @overload
    def serialize(
        self, compress: bool | None = ..., level: int | None = ...
    ) -> bytes: ...
    @overload
    def encode(self) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ...) -> bytes: ...
    @overload
    def encode(self, level: int | None = ...) -> bytes: ...
    @overload
    def encode(self, compress: bool | None = ..., level: int | None = ...) -> bytes: ...
    @staticmethod
    def deserialize(data: bytes) -> Expression: ...
    @staticmethod
    def decode(data: bytes) -> Expression: ...

class MatrixTranslator:
    @staticmethod
    def to_model(
        qubo: NDArray, name: str | None = ..., vtype: Vtype | None = ...
    ) -> Model: ...
    @staticmethod
    def to_dense(model: Model) -> NDArray: ...

class VariableOutOfRangeException(Exception):
    def __str__(self) -> str: ...

class VariableExistsException(Exception):
    def __str__(self) -> str: ...

class VariablesFromDifferentEnvsException(Exception):
    def __str__(self) -> str: ...

class DifferentEnvsException(Exception):
    def __str__(self) -> str: ...

class NoActiveEnvironmentFoundException(Exception):
    def __str__(self) -> str: ...

class MultipleActiveEnvironmentsException(Exception):
    def __str__(self) -> str: ...

class DecodeException(Exception):
    def __str__(self) -> str: ...

class ModelNotQuadraticException(Exception):
    def __str__(self) -> str: ...

class ModelNotUnconstrainedException(Exception):
    def __str__(self) -> str: ...
