import re
from pathlib import Path

print("✅ gen_stubs.py is running (root)")

# PROJECT CONFIGURATION 🔧
LIB_NAME = "aqmodels"  # top-level package name
# Set this manually, OR let the script auto-detect it:
LIB_ROOT = None  # e.g., Path("src/proj") or Path("proj")

# Map of target .pyi files to modules and symbols to extract from
# 🔧 Define what to extract and where to put it
# Format: destination_pyi_path: {source_module_name: [symbols]}
STUB_EXPORTS = {
    "aqmodels/__init__.pyi": {
        "_variable": ["Variable", "Bounds", "Vtype"],
        "_environment": ["Environment"],
        "_expression": ["Expression"],
    },
    # "aqmodels/translator/__init__.pyi": {
    #     "translator/_matrix_translator": ["MatrixTranslator"],
    # },
    # "proj/baz/__init__.pyi": {
    #     "_baz": ["Baz", "do_magic"],
    # },
}

PROJECT_ROOT = Path(__file__).resolve().parent.parent


def auto_detect_lib_root(lib_name: str) -> Path:
    """Try to find where the lib_name folder lives."""
    for path in PROJECT_ROOT.iterdir():
        candidate = path / lib_name
        if candidate.is_dir():
            return candidate
    raise FileNotFoundError(f"Could not auto-detect lib root for {lib_name}")


def extract_symbols(
    pyi_path: Path, names: list[str]
) -> tuple[list[str], list[str], bool]:
    """
    Extract imports and class/def blocks for given names.
    Returns: (import_lines, blocks, needs_future_annotations)
    """
    src = pyi_path.read_text(encoding="utf-8")
    lines = src.splitlines()

    import_lines = []
    symbol_blocks = []
    needs_future_annotations = False

    # Collect top-level import lines
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("import ") or stripped.startswith("from "):
            import_lines.append(stripped)
        elif stripped and not stripped.startswith("#"):
            break

    # Extract class/def blocks and check for self-references
    for name in names:
        pattern = re.compile(
            rf"^(class|def)\s+{re.escape(name)}\b.*?(?=^class|^def|\Z)",
            re.DOTALL | re.MULTILINE,
        )
        match = pattern.search(src)
        if not match:
            raise ValueError(f"Symbol `{name}` not found in {pyi_path}")
        block = match.group(0).rstrip()
        symbol_blocks.append(block + "\n")

        # Heuristic: look for `-> Name` inside the block
        if re.search(rf"->\s*{re.escape(name)}\b", block):
            needs_future_annotations = True

    return import_lines, symbol_blocks, needs_future_annotations


def generate_stubs():
    lib_root = LIB_ROOT or auto_detect_lib_root(LIB_NAME)
    print(f"🔧 Using LIB_ROOT = {lib_root.relative_to(PROJECT_ROOT)}")

    for dst_rel_path, module_map in STUB_EXPORTS.items():
        dst_path = lib_root.parent / dst_rel_path
        dst_path.parent.mkdir(parents=True, exist_ok=True)

        all_imports = set()
        all_exported_symbols = set()
        type_hints_need_future = False
        blocks = [
            "# This file is auto-generated by tools/gen_stubs.py",
            "# Do not edit manually.\n",
        ]

        module_blocks = []

        for mod, symbols in module_map.items():
            src_path = lib_root / f"{mod}.pyi"
            print(f"🔍 Extracting from {src_path.relative_to(PROJECT_ROOT)}")

            imports, symbols_code, needs_future_annotations = extract_symbols(
                src_path, symbols
            )
            all_imports.update(imports)
            all_exported_symbols.update(symbols)
            if needs_future_annotations:
                type_hints_need_future = True

            module_blocks.append(f"# From {mod}.pyi\n" + "\n".join(symbols_code))

        # Filter out imports that import symbols already defined
        filtered_imports = set()
        for line in all_imports:
            if line.startswith("from "):
                parts = line.split("import", 1)
                if len(parts) == 2:
                    imported = [s.strip().split(" as ")[0] for s in parts[1].split(",")]
                    if not any(sym in all_exported_symbols for sym in imported):
                        filtered_imports.add(line)
            else:
                filtered_imports.add(line)

        # Ensure __future__ import is inserted *at the top*
        ordered_imports = []
        if type_hints_need_future:
            ordered_imports.append("from __future__ import annotations")
        if filtered_imports:
            ordered_imports.extend(sorted(filtered_imports))

        # Add import block
        if ordered_imports:
            blocks.append("\n".join(ordered_imports))
            blocks.append("")

        blocks.extend(module_blocks)

        dst_path.write_text("\n".join(blocks), encoding="utf-8")
        print(f"✅ Wrote: {dst_path.relative_to(PROJECT_ROOT)}")


if __name__ == "__main__":
    print("✅ gen_stubs.py is running")
    exit(generate_stubs())
