import ast
import re
from pathlib import Path
from collections import defaultdict

# PROJECT CONFIGURATION 🔧
LIB_NAME = "aqmodels"  # top-level package name
# Set this manually, OR let the script auto-detect it:
LIB_ROOT = None  # e.g., Path("src/aqmodels") or Path("aqmodels")
PROJECT_ROOT = Path(__file__).resolve().parent.parent

if LIB_ROOT is None:
    for base in (PROJECT_ROOT / "src", PROJECT_ROOT):
        candidate = base / LIB_NAME
        if candidate.exists():
            LIB_ROOT = candidate
            break
    else:
        raise RuntimeError(f"Could not find library root for {LIB_NAME}")

EXPORT_RE = re.compile(r"#\s*@export(.*)")

AUTOGEN_HEADER = """# This file is auto-generated by tools/gen_init_py.py
# Do not edit manually.
"""

# Optional documentation blocks for __init__.py files
MODULE_DOCS = {
    "__init__": '"""Top-level API for aqmodels"""',
    # Add entries like "baz": "\"\"\"Submodule for baz functionality\"\"\""
}


def parse_exports(py_path: Path) -> list[dict]:
    """Extract exported classes and their target modules from a Python file."""
    exports = []
    text = py_path.read_text(encoding="utf-8")
    tree = ast.parse(text, filename=str(py_path))
    lines = text.splitlines()

    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            lineno = node.lineno - 1
            preceding = lines[lineno - 1].strip() if lineno > 0 else ""
            match = EXPORT_RE.search(preceding)
            if match:
                raw_target = match.group(1).strip()
                if not raw_target:
                    targets = ["__init__"]  # top-level
                else:
                    targets = [t.strip() for t in raw_target.split(",")]
                exports.append(
                    {
                        "class_name": node.name,
                        "module_path": py_path.relative_to(LIB_ROOT).with_suffix(""),
                        "targets": targets,
                    }
                )
    return exports


def generate_submodule_init(submodule: str, symbols: list[dict]):
    sub_path = LIB_ROOT / submodule / "__init__.py"
    sub_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [AUTOGEN_HEADER]

    if submodule in MODULE_DOCS:
        lines.append(MODULE_DOCS[submodule])
        lines.append("")

    import_lines = []
    assign_lines = []

    for sym_entry in symbols:
        sym = sym_entry["class_name"]
        mod_path = sym_entry["module_path"]
        import_path = (
            "." + ".".join(mod_path.parts[:-1]) if len(mod_path.parts) > 1 else ""
        )
        module_name = mod_path.name

        import_lines.append(
            f"from .._core import {sym} as __{sym}  # type: ignore[reportAttributeAccessIssue,attr-defined]"
        )
        import_lines.append(f"from {import_path}.{module_name} import {sym}")
        assign_lines.append(f"{sym} = __{sym}  # type: ignore[misc,assignment]\n")

    lines.extend(import_lines)
    lines.append("")
    lines.extend(assign_lines)

    lines.append("__all__ = [")
    for sym_entry in symbols:
        lines.append(f"    \"{sym_entry['class_name']}\",")
    lines.append("]\n")

    sub_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"✅ Wrote submodule: {sub_path.relative_to(PROJECT_ROOT)}")


def generate_top_level_init(exports: list[dict]):
    by_target = defaultdict(list)
    for e in exports:
        for target in e["targets"]:
            by_target[target].append(e)

    top_path = LIB_ROOT / "__init__.py"
    lines = [AUTOGEN_HEADER]

    if "__init__" in MODULE_DOCS:
        lines.append(MODULE_DOCS["__init__"])
        lines.append("")

    submodules_used = set()
    top_level_symbols = []

    import_lines = []
    assign_lines = []

    # First, handle all top-level bindings
    for e in by_target["__init__"]:
        sym = e["class_name"]
        mod = e["module_path"]
        mod_base = mod.name
        import_lines.append(
            f"from ._core import {sym} as __{sym}  # type: ignore[reportAttributeAccessIssue]"
        )
        import_lines.append(f"from .{mod_base} import {sym}")
        assign_lines.append(f"{sym} = __{sym}  # type: ignore[misc,assignment]\n")
        top_level_symbols.append(sym)

    # Then, handle submodules (and optional top-level re-exports)
    for target, entries in by_target.items():
        if target == "__init__":
            continue
        submodules_used.add(target)
        import_lines.append(f"from . import {target}")
        for e in entries:
            sym = e["class_name"]
            import_lines.append(f"from .{target} import {sym}")
            top_level_symbols.append(sym)

    lines.extend(import_lines)
    lines.append("")
    lines.extend(assign_lines)

    # Final __all__
    all_entries = list(submodules_used) + top_level_symbols
    lines.append("__all__ = [")
    for sym in all_entries:
        lines.append(f'    "{sym}",')
    lines.append("]\n")

    top_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"✅ Wrote top-level: {top_path.relative_to(PROJECT_ROOT)}")


def main():
    exports: list[dict] = []
    for path in LIB_ROOT.rglob("_*.py"):
        exports += parse_exports(path)

    # Generate submodules first
    sub_exports = defaultdict(list)
    for e in exports:
        for t in e["targets"]:
            if t != "__init__":
                sub_exports[t].append(e)

    for sub, symbol_list in sub_exports.items():
        generate_submodule_init(sub, symbol_list)

    generate_top_level_init(exports)


if __name__ == "__main__":
    exit(main())
